export { default as Header } from './Header'
export { default as Content } from './Content'
export { default as Total } from './Total'
export { default as Part1 } from './Part1'
export { default as Part2 } from './Part2'
export { default as Part3 } from './Part3'