POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "daudzkie",
    "password": "tinuod"
}


### Wrong password
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "daudzkie",
    "password": "bakakon"
}